# Generated by Django 2.1.3 on 2018-12-09 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Czat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL)),
                ('odbiorca', models.ManyToManyField(related_name='odbiorca', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='komentarz_do_miejsca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('tresc', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='komentarz_do_ogloszenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('tresc', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='komentarz_do_wydarzenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('tresc', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='miejsce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=100)),
                ('nazwa', models.CharField(max_length=50)),
                ('godzina_otwarcia', models.TimeField(blank=True, default=None, null=True)),
                ('godzina_zamkniecia', models.TimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ogloszenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=20)),
                ('data', models.DateTimeField(auto_now=True)),
                ('opis', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Powiadomienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='wiadomosc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiadomosc', to=settings.AUTH_USER_MODEL)),
                ('czat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Czat')),
            ],
        ),
        migrations.CreateModel(
            name='wydarzenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('data_rozpoczecia', models.DateField()),
                ('opis', models.TextField()),
                ('miejsce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.miejsce')),
                ('organizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wydarzenia', to=settings.AUTH_USER_MODEL)),
                ('uczestnicy', models.ManyToManyField(related_name='uczestnicy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='powiadomienie',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.wydarzenie'),
        ),
        migrations.AddField(
            model_name='powiadomienie',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='komentarz_do_wydarzenia',
            name='wydarzenie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.wydarzenie'),
        ),
        migrations.AddField(
            model_name='komentarz_do_ogloszenia',
            name='ogleoszenie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.ogloszenie'),
        ),
        migrations.AddField(
            model_name='komentarz_do_miejsca',
            name='miejsce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.miejsce'),
        ),
    ]
