# Generated by Django 2.1.3 on 2019-01-03 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='czat',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='czat',
            name='odbiorca',
        ),
        migrations.RemoveField(
            model_name='wiadomosc',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='wiadomosc',
            name='czat',
        ),
        migrations.DeleteModel(
            name='Czat',
        ),
        migrations.DeleteModel(
            name='wiadomosc',
        ),
    ]
