# Generated by Django 2.1.3 on 2019-01-05 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_friends'),
        ('event', '0002_auto_20190103_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Czat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='czat', max_length=255, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_czatu', to='account.Profile')),
                ('uzytkownicy', models.ManyToManyField(to='account.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Wiadomosc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.CharField(max_length=255)),
                ('data_utworzenia', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiadomosci', to='account.Profile')),
                ('czat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Czat')),
            ],
        ),
    ]
