# Generated by Django 2.1.3 on 2019-01-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_czat_wiadomosc'),
    ]

    operations = [
        migrations.AddField(
            model_name='powiadomienie',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Czat'),
        ),
        migrations.AlterField(
            model_name='powiadomienie',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.wydarzenie'),
        ),
    ]
