# Generated by Django 2.1.3 on 2019-01-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20190105_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='miejsce',
            name='zaakcaptowane',
            field=models.BooleanField(default=False),
        ),
    ]
