# Generated by Django 2.1.3 on 2019-01-05 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_miejsce_zaakcaptowane'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miejsce',
            options={'verbose_name': 'Miejsce', 'verbose_name_plural': 'Miejsca'},
        ),
        migrations.RenameField(
            model_name='miejsce',
            old_name='zaakcaptowane',
            new_name='zaakceptowane',
        ),
    ]
