# Generated by Django 2.1.3 on 2019-01-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20190105_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiadomosc',
            name='tresc',
            field=models.TextField(max_length=255),
        ),
    ]
