# Generated by Django 2.1.3 on 2019-01-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20190105_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='komentarz_do_ogloszenia',
            old_name='ogleoszenie',
            new_name='ogloszenie',
        ),
    ]
