# Generated by Django 2.1.4 on 2019-03-09 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_friends'),
        ('event', '0010_auto_20190125_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zaproszenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_Zaproszenia', to='account.Profile')),
                ('uzytkownicyy', models.ManyToManyField(related_name='Zaproszony', to='account.Profile')),
            ],
        ),
    ]
