# Generated by Django 2.1.3 on 2019-03-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20190125_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='miejsce',
            name='photo',
            field=models.ImageField(blank=True, default='miejsca/Default.jpg', upload_to='miejsca/%Y/%m/%d'),
        ),
    ]
