# Generated by Django 2.1.4 on 2019-03-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_zaproszenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaproszenia',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='zaproszenia',
            name='tresc',
            field=models.TextField(null=True),
        ),
    ]
