# Generated by Django 2.1.3 on 2019-03-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20190323_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='wydarzenie',
            name='photo',
            field=models.ImageField(blank=True, default='miejsca/Default.jpg', upload_to='wydarzenia/'),
        ),
    ]
