# Generated by Django 2.1.3 on 2019-03-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20190310_1415'),
        ('event', '0014_wydarzenie_photo'),
    ]

    operations = [
    ]
