# Generated by Django 2.1.3 on 2019-03-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20190324_1417'),
        ('event', '0015_merge_20190323_1807'),
    ]

    operations = [
    ]
