# Generated by Django 2.1.3 on 2019-03-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_merge_20190324_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogloszenie',
            name='zdjecie',
            field=models.ImageField(blank=True, default='ogloszenie/Default.jpg', upload_to='ogloszenie/'),
        ),
    ]
