# Generated by Django 2.1.3 on 2019-03-30 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_rate'),
        ('event', '0017_ogloszenie_zdjecie'),
    ]

    operations = [
        migrations.CreateModel(
            name='rate_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluated', to='account.Profile')),
                ('evaluative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluative', to='account.Profile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.wydarzenie')),
            ],
        ),
    ]
