# Generated by Django 2.1.4 on 2019-04-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_ocena_wydarzenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='wydarzenie',
            name='Srednia_ocen',
            field=models.IntegerField(default=0),
        ),
    ]
